== Blue/Green

https://martinfowler.com/bliki/BlueGreenDeployment.html[Description of Blue/Green Deployment]

Make sure you are in the correct namespace

:section-k8s: bluegreen
:set-namespace: myspace

include::partial$set-context.adoc[]


Make sure nothing else is deployed:

[#no-resources-blue-green]
[source, bash]
----
kubectl get all
----
copyToClipboard::no-resources-blue-green[]

----
No resources found in myspace namespace.
----

Deploy V1 of `myboot`:

[#deploy-v1-blue-green]
[source, bash]
----
kubectl apply -f apps/kubefiles/myboot-deployment-resources-limits.yml
----
copyToClipboard::deploy-v1-blue-green[]

Scale to 2 replicas:

[#scale-v1-blue-green]
[source, bash]
----
kubectl scale deployment/myboot --replicas=2
----
copyToClipboard::scale-v1-blue-green[]

Watch and `show-labels`:

[#labels-v1-blue-green]
[source, bash]
----
watch kubectl get pods --show-labels
----
copyToClipboard::labels-v1-blue-green[]

Deploy the service:

[#deploy-service-blue-green]
[source, bash]
----
kubectl apply -f apps/kubefiles/myboot-service.yml
----
copyToClipboard::deploy-service-blue-green[]

:section-k8s: bluegreen
:service-exposed: myboot
include::partial$env-curl.adoc[]

And run loop script:

include::partial$loop.adoc[]

Deploy V2 of `myboot`:

[#deploy-v2-blue-green]
[source, bash]
----
kubectl apply -f apps/kubefiles/myboot-deployment-resources-limits-v2.yml
----
copyToClipboard::deploy-v2-blue-green[]

Verify that the new pod/deployment carries the new code:

[#exec-v2-blue-green]
[source, bash]
----
PODNAME=$(kubectl get pod -l app=myboot-next -o name)
kubectl exec -it $PODNAME -- curl localhost:8080
----
copyToClipboard::exec-v2-blue-green[]

----
Bonjour from Spring Boot! 1 on myboot-next-66b68c6659-ftcjr
----

Now update the single Service to point to the new pod and go GREEN:

[#patch-service-green]
[source,bash,subs="+macros,+attributes"]
----
kubectl patch svc/myboot -p '{"spec":{"selector":{"app":"myboot-next"}}}'
----
copyToClipboard::patch-service-green[]

----
Aloha from Spring Boot! 240 on myboot-d78fb6d58-929wn
Bonjour from Spring Boot! 2 on myboot-next-66b68c6659-ftcjr
Bonjour from Spring Boot! 3 on myboot-next-66b68c6659-ftcjr
Bonjour from Spring Boot! 4 on myboot-next-66b68c6659-ftcjr
----

Determine that you prefer Hawaiian (blue) to French (green) and fallback:

Now update the single Service to point to the new pod and go BLUE:

[#patch-service-blue]
[source,bash,subs="+macros,+attributes"]
----
kubectl patch svc/myboot -p '{"spec":{"selector":{"app":"myboot"}}}'
----
copyToClipboard::patch-service-blue[]

----
Bonjour from Spring Boot! 17 on myboot-next-66b68c6659-ftcjr
Aloha from Spring Boot! 257 on myboot-d78fb6d58-vqvlb
Aloha from Spring Boot! 258 on myboot-d78fb6d58-vqvlb
----

== Clean Up

[#clean]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete service myboot
kubectl delete deployment myboot
kubectl delete deployment myboot-next
----
copyToClipboard::clean[]