= ConfigMap

ConfigMap is the Kubernetes resource that allows you to externalize your application's configuration.

*_An app’s config is everything that is likely to vary between deploys (staging, production, developer environments, etc)._*

https://12factor.net/config[12 Factor Apps]

== Environment Variables

MyRESTController.java includes a small chunk of code that looks to the environment

[source,java]
----
   @RequestMapping("/configure")
   public String configure() {
        String databaseConn = environment.getProperty("DBCONN","Default");
        String msgBroker = environment.getProperty("MSGBROKER","Default");
        String hello = environment.getProperty("GREETING","Default");
        String love = environment.getProperty("LOVE","Default");
        return "Configuration: \n"
            + "databaseConn=" + databaseConn + "\n"
            + "msgBroker=" + msgBroker + "\n"
            + "hello=" + hello + "\n"
            + "love=" + love + "\n";
   }
----

Environment variables can be manipulated at the Deployment level. 
Changes cause Pod redeployment.

Deploy `myboot`:

[#deploy-myboot-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-deployment.yml
----

Deploy `myboot` Service:

[#deploy-myboot-service-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-service.yml
----

And watch the pods status:

:section-k8s: configmap
include::partial$watching-pods.adoc[]

Ask the application for its configuration:

:section-k8s: configmaps
:service-exposed: myboot
include::partial$env-curl.adoc[]

[#get-config-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-jsbz7
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----

== Set Environment Variables

[#set-env-vars]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl set env deployment/myboot GREETING="namaste" \
  LOVE="Aloha" \
  DBCONN="jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;"
----

Watch the pods being reborn:

[.console-output]
[source,bash]
----
NAME                      READY   STATUS        RESTARTS   AGE
myboot-66d7d57687-jsbz7   1/1     Terminating   0          5m
myboot-785ff6bddc-ghwpc   1/1     Running       0          13s
----

[#get-config2-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-5fd9dd9c59-58xbh
databaseConn=jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
msgBroker=Default
greeting=namaste
love=Aloha
----

Describe the deployment:

:section-k8s: configmaps
:describe-deployment-name: myboot

include::partial$describe-deployment.adoc[]

[.console-output]
[source,bash]
----
...
  Containers:
   myboot:
    Image:      quay.io/burrsutter/myboot:v1
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      GREETING:  namaste
      LOVE:      Aloha
      DBCONN:    jdbc:sqlserver://45.91.12.123:1443;user=MyUserName;password=*****;
    Mounts:      <none>
  Volumes:       <none>
...  
----

Remove environment variables:

[#remove-env-vars-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl set env deployment/myboot GREETING- \
  LOVE- \
  DBCONN-
----

And verify that they have been removed:

[#get-config3-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-66d7d57687-xkgw6
databaseConn=Default
msgBroker=Default
greeting=Default
love=Default
----

==  Create a ConfigMap

[#create-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create cm my-config --from-env-file=apps/config/some.properties
----

[#get-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get cm
kubectl get cm my-config
kubectl get cm my-config -o json
----

[.console-output]
[source,bash]
----
...
    "data": {
        "GREETING": "jambo",
        "LOVE": "Amour"
    },
    "kind": "ConfigMap",
...    
----

Or you can describe the `ConfigMap` object:

[#describe-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl describe cm my-config
----

[.console-output]
[source,bash]
----
Name:         my-config
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Data
====
GREETING:
====
jambo
LOVE:
====
Amour
Events:  <none>
----

.Using `kubectl edit` to view resources
****
For large files you might find using `kubectl edit` is more convenient for viewing resources on the cluster.  In our case, we can view the config map by running the following (and aborting any changes!):

include::partial$tip_vscode_kube_editor.adoc[]

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl edit cm my-config
----
****

Now deploy the app with its request for the `ConfigMap`:

[#deploy-myboot-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-deployment-configuration.yml
----

And get its configure endpoint:

[#get-config4-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-84bfcff474-x6xnt
databaseConn=Default
msgBroker=Default
greeting=jambo
love=Amour
----

And switch to the other properties file by recreating the `ConfigMap`:

[#delete-pod-configmap-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete cm my-config
kubectl create cm my-config --from-env-file=apps/config/other.properties
kubectl delete pod -l app=myboot --wait=false
----

[#get-config5-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT/configure
----

[.console-output]
[source,bash]
----
Configuration for : myboot-694954fc6d-nzdvx
databaseConn=jdbc:sqlserver://123.123.123.123:1443;user=MyUserName;password=*****;
msgBroker=tcp://localhost:61616?jms.useAsyncSend=true
hello=Default
love=Default
----

There are a lot more ways to have fun with ConfigMaps, the core documentation has you manipulate a Pod specification instead of a Deployment but the results are basically the same
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap


== Clean Up

[#clean-configmaps]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete deployment myboot
kubectl delete cm my-config
kubectl delete service myboot
----
