= Logs

There are various "production-ready" ways to do log gathering and viewing across a Kubernetes/OpenShift cluster. Many folks like some flavor of ELK (ElasticSearch, Logstash, Kibana) or EFK (ElasticSearch, FluentD, Kibana).

The focus here is on things a developer needs to get access to do in order to help understand the behavior of their application running inside of a pod.

Make sure you have an application (Deployment) running:

[#create-deployment]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        env: dev
    spec:
      containers:
      - name: myapp
        image: quay.io/rhdevelopers/myboot:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
EOF
----

Make sure you are running 3 replicas (3 pods/instances of your application):

[#logs-get-replicas]
[.console-input]
[source, bash]
----
kubectl get deployment my-deployment -o jsonpath='{.status.replicas}{"\n"}'
----

If not, scale up to 3:

[#logs-scale-replicas]
[.console-input]
[source, bash]
----
kubectl scale --replicas=3 deployment/my-deployment
----

[.console-output]
[source,bash]
----
NAME                             READY   STATUS    RESTARTS   AGE
my-deployment-5dc67997c7-5bq4n   1/1     Running   0          34s
my-deployment-5dc67997c7-m7z9f   1/1     Running   0          34s
my-deployment-5dc67997c7-s4jc6   1/1     Running   0          34s
----

[#logs-log-deployment]
[.console-input]
[source, bash]
----
kubectl logs my-deployment-5dc67997c7-m7z9f
----

[.console-output]
[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)

----

You can follow logs with `-f` parameter:

[#logs-log-deployment-follow]
[.console-input]
[source, bash]
----
kubectl logs my-deployment-5dc67997c7-m7z9f -f
----

And in another Terminal:

[.console-input]
[source,bash]
----
kubectl exec -it my-deployment-5dc67997c7-m7z9f -- /bin/bash
curl localhost:8080
----

[.console-output]
[source,bash]
----
Aloha from my-deployment-5dc67997c7-m7z9f
----

Deploy a Service for `my-deployment`:

[#create-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: the-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
EOF
----

In another Terminal, loop and curl that service:

:section-k8s: logs
:service-exposed: the-service
include::partial$env-curl.adoc[]

Start sending the request in a loop:

include::partial$loop.adoc[]

Show the logs from all pods appending the `--all-pods` option:

[#all-pods]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl logs -f deployments/my-deployment --all-pods
----

[.console-output]
[source,bash]
----
my-deployment-5dc67997c7-5bq4n myapp Aloha from my-deployment-5dc67997c7-5bq4n
my-deployment-5dc67997c7-m7z9f myapp Aloha from my-deployment-5dc67997c7-m7z9f
my-deployment-5dc67997c7-s4jc6 myapp Aloha from my-deployment-5dc67997c7-s4jc6
my-deployment-5dc67997c7-s4jc6 myapp Aloha from my-deployment-5dc67997c7-s4jc6
----

Other popular tools to show the logs are:

. https://github.com/wercker/stern[stern]
. https://github.com/boz/kail[kail]:

[TIP]
====
To potentially pull the logs from a failing pod use `-p`

[.console-input]
[source,bash]
----
kubectl logs my-deployment-5dc67997c7-s4jc6 -p 
----
====

== Clean Up

[#clean-up]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete service the-service
kubectl delete deployment my-deployment
----
