= Pod, ReplicaSet, Deployment

First create a namespace to work in:

[#create-namespace]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace myspace
kubectl config set-context --current --namespace=myspace
# OR
kubens myspace
----
copyToClipboard::create-namespace[]

== Pod

Create a https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs[naked pod]:

[#create-pod]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: quarkus-demo
spec:
  containers:
  - name: quarkus-demo
    image: quay.io/rhdevelopers/quarkus-demo:v1
EOF
----
copyToClipboard::create-pod[]

Watch the pod lifecycle:

[#watch-pod]
[source,bash,subs="+macros,+attributes"]
----
watch kubectl get pods
----
copyToClipboard::watch-pod[]

----
NAME           READY   STATUS              RESTARTS   AGE
quarkus-demo   0/1     ContainerCreating   0          10s
----

From ContainerCreating to Running with Ready 1/1:

----
NAME           READY   STATUS    RESTARTS   AGE
quarkus-demo   1/1     Running   0          18s
----

Verify the application in the Pod:

[#verify-pod]
[source,bash,subs="+macros,+attributes"]
----
kubectl exec -it quarkus-demo /bin/sh
----
copyToClipboard::verify-pod[]

Run the next command.
Notice that as you are inside the container instance, the hostname is `localhost`.

[#curl-inside-pod]
[source,bash]
----
curl localhost:8080
----
copyToClipboard::curl-inside-pod[]

----
Supersonic Subatomic Java with Quarkus quarkus-demo:1
exit
----

Let's delete the previous Pod:

[#delete-naked-pod]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete pod quarkus-demo
----
copyToClipboard::delete-naked-pod[]

[#watch-all-naked-pod]
[source,bash]
----
watch kubectl get pods
----
copyToClipboard::watch-all-naked-pod[]

----
NAME           READY   STATUS        RESTARTS   AGE
quarkus-demo   0/1     Terminating   0          9m35s

No resources found in myspace namespace.
----

A Naked Pod disappears forever.

== ReplicaSet

Create a ReplicaSet:

[#create-replicaset]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs-quarkus-demo
spec:
    replicas: 3
    selector:
       matchLabels:
          app: quarkus-demo
    template:
       metadata:
          labels:
             app: quarkus-demo
             env: dev
       spec:
          containers:
          - name: quarkus-demo
            image: quay.io/burrsutter/quarkus-demo:1.0.0
EOF
----
copyToClipboard::create-replicaset[]

Get the pods with labels:

[#replicaset-show-labels]
[source,bash,subs="+macros,+attributes"]
----
watch kubectl get pods --show-labels
----
copyToClipboard::replicaset-show-labels[]

----
NAME                    READY   STATUS    RESTARTS   AGE   LABELS
rs-quarkus-demo-jd6jk   1/1     Running   0          58s   app=quarkus-demo,env=dev
rs-quarkus-demo-mlnng   1/1     Running   0          58s   app=quarkus-demo,env=dev
rs-quarkus-demo-t26gt   1/1     Running   0          58s   app=quarkus-demo,env=dev
----

[#get-rs]
[source,bash,subs="+macros,+attributes"]
----
kubectl get rs
----
copyToClipboard::get-rs[]

----
NAME              DESIRED   CURRENT   READY   AGE
rs-quarkus-demo   3         3         3       79s
----

Describe the RS:

[#describe-rs-quarkus-demo]
[source,bash]
----
kubectl describe rs rs-quarkus-demo
----
copyToClipboard::describe-rs-quarkus-demo[]

----
Name:         rs-quarkus-demo
Namespace:    myspace
Selector:     app=quarkus-demo
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"name":"rs-quarkus-demo","namespace":"myspace"},"spec":{"replicas...
Replicas:     3 current / 3 desired
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=quarkus-demo
           env=dev
  Containers:
   quarkus-demo:
    Image:        quay.io/burrsutter/quarkus-demo:1.0.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-jd6jk
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-t26gt
  Normal  SuccessfulCreate  89s   replicaset-controller  Created pod: rs-quarkus-demo-mlnng
----

Pods are "owned" by the ReplicaSet:

[#rs-owned-ref]
[source,bash]
----
kubectl get pod rs-quarkus-demo-mlnng -o json | jq ".metadata.ownerReferences[]"
----
copyToClipboard::rs-owned-ref[]

----
{
  "apiVersion": "apps/v1",
  "blockOwnerDeletion": true,
  "controller": true,
  "kind": "ReplicaSet",
  "name": "rs-quarkus-demo",
  "uid": "1ed3bb94-dfa5-40ef-8f32-fbc9cf265324"
}
----

Now delete a pod, while watching pods:

[#delete-pod-rs]
[source,bash]
----
kubectl delete pod rs-quarkus-demo-mlnng
----
copyToClipboard::delete-pod-rs[]

And a new pod will spring to life to replace it:

----
NAME                    READY   STATUS              RESTARTS   AGE    LABELS
rs-quarkus-demo-2txwk   0/1     ContainerCreating   0          2s     app=quarkus-demo,env=dev
rs-quarkus-demo-jd6jk   1/1     Running             0          109s   app=quarkus-demo,env=dev
rs-quarkus-demo-t26gt   1/1     Running             0          109s   app=quarkus-demo,env=dev
----

Delete the ReplicaSet to remove all the associated pods:

[#delete-rs]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete rs rs-quarkus-demo
----
copyToClipboard::delete-rs[]

== Deployment

[#create-deployment]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-demo
  template:
    metadata:
      labels:
        app: quarkus-demo
        env: dev
    spec:
      containers:
      - name: quarkus-demo
        image: quay.io/burrsutter/quarkus-demo:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
EOF
----
copyToClipboard::create-deployment[]

[#pod-show-labels-dep]
[source,bash]
----
kubectl get pods --show-labels
----
copyToClipboard::pod-show-labels-dep[]

----
NAME                                       READY   STATUS    RESTARTS   AGE   LABELS
quarkus-demo-deployment-5979886fb7-c888m   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886fb7
quarkus-demo-deployment-5979886fb7-gdtnz   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886fb7
quarkus-demo-deployment-5979886fb7-grf59   1/1     Running   0          17s   app=quarkus-demo,env=dev,pod-template-hash=5979886f
----

[#exec-inside-pod-labels]
[source,bash]
----
kubectl exec -it quarkus-demo-deployment-5979886fb7-c888m -- curl localhost:8080
----
copyToClipboard::exec-inside-pod-labels[]

----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-c888m:1
----

In the next section, you'll learn the concept of `Service`.
This is an important element in Kubernetes ecosystem.