== Rolling updates

Make sure you are in the correct namespace

----
kubectl config set-context --current --namespace=myspace
----

Deploy the Spring Boot app if needed

----
kubectl apply -f apps/kubefiles/myboot-deployment-resources-limits.yml
kubectl apply -f apps/kubefiles/myboot-service.yml
----

Terminal 1: watch the pods
----
watch kubectl get pods
----

Terminal 2: curl loop the service
OpenShift:
[#openshift-ip-port]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service myboot -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
PORT=$(kubectl get service myboot -o jsonpath="{.spec.ports[*].port}")
----
copyToClipboard::openshift-ip-port[]

OR

Minikube:
[#minikube-ip-port]
[source,bash,subs="+macros,+attributes"]
----
IP=$(minikube ip)
PORT=$(kubectl get service/myboot -o jsonpath="{.spec.ports[*].nodePort}")
----
copyToClipboard::minikube-ip-port[]

[#curl-loop]
[source,bash,subs="+macros,+attributes"]
----
while true
do curl $IP:$PORT
sleep .3
done
----
copyToClipboard::curl-loop[]

Describe the Deployment
----
kubectl describe deployment myboot
.
.
.
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
.
.
.
----

StrategyType options include RollingUpdate and Recreate

Change the replicas
----
export KUBE_EDITOR="code -w"
kubectl edit deployment myboot
----

Look for "replicas"
----
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myboot
---

And update to "2"
----
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myboot
---

Save and close the VS Code window and a new pod will come to life
----
NAME                     READY   STATUS    RESTARTS   AGE
myboot-d78fb6d58-2fqml   1/1     Running   0          25s
myboot-d78fb6d58-ljkjp   1/1     Running   0          3m
----

Change the image associated with the deployment

----
kubectl edit deployment myboot
----

Find the image attribute
----
    spec:
      containers:
      - image: quay.io/burrsutter/myboot:v1
        imagePullPolicy: IfNotPresent
        name: myboot
----

and change the image `myboot:v2`

----
    spec:
      containers:
      - image: quay.io/burrsutter/myboot:v2
        imagePullPolicy: IfNotPresent
        name: myboot
----

----
NAME                      READY   STATUS              RESTARTS   AGE
myboot-7fbc4b97df-4ntmk   1/1     Running             0          9s
myboot-7fbc4b97df-qtkzj   0/1     ContainerCreating   0          0s
myboot-d78fb6d58-2fqml    1/1     Running             0          3m29s
myboot-d78fb6d58-ljkjp    1/1     Terminating         0          8m
----

----
Aloha from Spring Boot! 211 on myboot-d78fb6d58-2fqml
Aloha from Spring Boot! 212 on myboot-d78fb6d58-2fqml
Bonjour from Spring Boot! 0 on myboot-7fbc4b97df-4ntmk
Bonjour from Spring Boot! 1 on myboot-7fbc4b97df-4ntmk
----

Check the status
----
kubectl rollout status deployment myboot
deployment "myboot" successfully rolled out
----

Notice the new RS
----
kubectl get rs
NAME                DESIRED   CURRENT   READY   AGE
myboot-7fbc4b97df   2         2         2       116s
myboot-d78fb6d58    0         0         0       10m
----

Describe the Deployment
----
kubectl describe deployment myboot
----

And check out the Events section
----
...
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  16m    deployment-controller  Scaled up replica set myboot-d78fb6d58 to 1
  Normal  ScalingReplicaSet  6m15s  deployment-controller  Scaled up replica set myboot-d78fb6d58 to 2
  Normal  ScalingReplicaSet  2m55s  deployment-controller  Scaled up replica set myboot-7fbc4b97df to 1
  Normal  ScalingReplicaSet  2m46s  deployment-controller  Scaled down replica set myboot-d78fb6d58 to 1
  Normal  ScalingReplicaSet  2m46s  deployment-controller  Scaled up replica set myboot-7fbc4b97df to 2
  Normal  ScalingReplicaSet  2m37s  deployment-controller  Scaled down replica set myboot-d78fb6d58 to 0
----

Rollback to v1
----
kubectl set image deployment myboot myboot=quay.io/burrsutter/myboot:v1
----

and it rolls back to Aloha

----
Bonjour from Spring Boot! 501 on myboot-7fbc4b97df-qtkzj
Bonjour from Spring Boot! 502 on myboot-7fbc4b97df-qtkzj
Aloha from Spring Boot! 0 on myboot-d78fb6d58-vnlch
----

