= Secrets
Make sure you are in the correct namespace:

:section-k8s: resource
:set-namespace: myspace

include::partial$namespace-setup-tip.adoc[]

include::partial$set-context.adoc[]

Make sure nothing is running in your namespace:

[#no-resources-resource]
[.console-input]
[source, bash]
----
kubectl get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----

Deploy `myboot` service:

[#deploy-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-deployment.yml
----

Deploy myboot Service:

[#service-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-service.yml
----

Watch Pods:

:section-k8s: secrets
include::partial$watching-pods.adoc[]

Send a request:

:section-k8s: secrets
:service-exposed: myboot
include::partial$env-curl.adoc[]

The ConfigMap example earlier had an example of a database connection string ("user=MyUserName;password=*****"). Sensistive data like passwords can place in a different vessel known as a Secret.

== Creating Secrets

[#create-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create secret generic mysecret --from-literal=user='MyUserName' --from-literal=password='mypassword'
----

[#get-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secrets
----

[.console-output]
[source,bash]
----
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-96ml5    kubernetes.io/dockercfg               1      3d6h
builder-token-h5g82        kubernetes.io/service-account-token   4      3d6h
builder-token-vqjqz        kubernetes.io/service-account-token   4      3d6h
default-dockercfg-bsnjr    kubernetes.io/dockercfg               1      3d6h
default-token-bl77s        kubernetes.io/service-account-token   4      3d6h
default-token-vlzsl        kubernetes.io/service-account-token   4      3d6h
deployer-dockercfg-k6npn   kubernetes.io/dockercfg               1      3d6h
deployer-token-4hb78       kubernetes.io/service-account-token   4      3d6h
deployer-token-vvh6r       kubernetes.io/service-account-token   4      3d6h
mysecret                   Opaque                                2      5s
----

The user & password are not immediately visible:

[#describe-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl describe secret mysecret
----

[.console-output]
[source,bash]
----
Name:         mysecret
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  10 bytes
user:      10 bytes
----

[#get-secret-cli-yaml-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o yaml
----

[source, yaml]
----
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  user: TXlVc2VyTmFtZQ==
kind: Secret
metadata:
  creationTimestamp: "2020-03-31T20:19:26Z"
  name: mysecret
  namespace: myspace
  resourceVersion: "4944690"
  selfLink: /api/v1/namespaces/myspace/secrets/mysecret
  uid: e8c5f12e-bd71-4d6b-8d8c-7af9ed6439f8
type: Opaque
----

You can see the secrets by running:

[#get-secret-cli-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'bXlwYXNzd29yZA==' | base64 --decode
----

[.console-output]
[source,bash]
----
mypassword
----

[#get-secret-cli-username-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'TXlVc2VyTmFtZQ==' | base64 --decode
----

[.console-output]
[source,bash]
----
MyUserName
----

Or get them using `kubectl`:

[#get-secret-kubectl-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o jsonpath='{.data.password}' | base64 --decode 
----

Secrets are provided to the Pod via Volume Mounts:

[source, yaml]
----
        volumeMounts:          
          - name: mysecretvolume
            mountPath: /mystuff/mysecretvolume
----

New deployment with the secret volume:

[#replace-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl replace -f apps/kubefiles/myboot-deployment-configuration-secret.yml
----

Exec into the newly created Pod:

[#print-secrets-volume-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(kubectl get pod -l app=myboot --field-selector pass:['status.phase!=Terminating'] -o name)
kubectl exec $PODNAME -- cat /mystuff/secretstuff/password
----

Results in:

[.console-output]
[source,bash]
----
mypassword
----

You could provide the location of `/mystuff/mysecretvolume` to the pod via an environment variable so the application knows where to go looking.

More information on https://kubernetes.io/docs/concepts/configuration/secret/[Secrets]

== Clean Up

[.console-input]
[source,bash]
----
kubectl delete deployment myboot
kubectl delete service myboot
----



