= Secrets
include::_attributes.adoc[]
:watch-terminal: Terminal 2

Secrets are an out of the box way Kubernetes provides to store sensitive data.  Most similar to config maps, these are treated with a bit of extra care under the hood in Kubernetes.

Secrets are meant to give developers a way of specifying common types of sensitive data (basic-auth credentials, image registry credentials, tls certs, etc) without including it (insecurely) in the code (application or infrastructure) of their containerized application.  A typical generic secret that one will come across are the credentials for accessing a database.

The heart of any secret is not displayed in plain-text by default.  Instead, secret data is base64 encoded and needs to be decoded to be read.

[WARNING]
====
Like most data in the Kubernetes API, secrets are stored within the `etc` distributed data store.  Whilst access to this data is mediated by the cluster's RBAC, it should be noted that Secrets are NOT encrypted at rest within `etcd` in Kubernetes by default.  This can be enabled on generic kubernetes by following link:https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[these instructions^].  OpenShift makes this even easier as documented link:https://docs.openshift.com/container-platform/4.7/security/encrypting-etcd.html[here^]
====

== Prerequisites

Make sure you are in the correct namespace:

:section-k8s: resource
:set-namespace: myspace

include::partial$namespace-setup-tip.adoc[]

include::partial$set-context.adoc[]

Make sure nothing is running in your namespace:

[#no-resources-resource]
[.console-input]
[source, bash]
----
kubectl get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----

Deploy `myboot` service:

[#deploy-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-deployment.yml
----

Deploy myboot Service:

[#service-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-service.yml
----

In a separate terminal (hereafter referred to as *{watch-terminal}*) setup a watch on the pods: 

:section-k8s: secrets
include::partial$watching-pods-with-nodes.adoc[]

Meanwhile, in the main terminal, send a request:

:service-exposed: myboot
include::partial$env-curl.adoc[]

which should give us the by now familiar response

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Aloha from Spring Boot! 1 on myboot-7cbfbd9b89-dl2hv
----

== Creating Secrets

Previously, we used a `ConfigMap` to hold a database connection string ("user=MyUserName;password=*****"). Instead, let's create a secret to hold this sensistive data.

The `kubectl` CLI has some support for creating generic (or `opaque`) secrets like the one we would use for a database login. 

[#create-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create secret generic mysecret --from-literal=user='MyUserName' --from-literal=password='mypassword'
----

[#get-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secrets
----

Which will now yield output something like the following

[tabs]
====
Minikube::
+
--
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME                  TYPE                                  DATA   AGE
default-token-nxkpw   kubernetes.io/service-account-token   3      5d12h
mysecret              Opaque                                2      25s
----
--
OpenShift::
+
--
[.console-output]
[source,bash]
----
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-96ml5    kubernetes.io/dockercfg               1      3d6h
builder-token-h5g82        kubernetes.io/service-account-token   4      3d6h
builder-token-vqjqz        kubernetes.io/service-account-token   4      3d6h
default-dockercfg-bsnjr    kubernetes.io/dockercfg               1      3d6h
default-token-bl77s        kubernetes.io/service-account-token   4      3d6h
default-token-vlzsl        kubernetes.io/service-account-token   4      3d6h
deployer-dockercfg-k6npn   kubernetes.io/dockercfg               1      3d6h
deployer-token-4hb78       kubernetes.io/service-account-token   4      3d6h
deployer-token-vvh6r       kubernetes.io/service-account-token   4      3d6h
mysecret                   Opaque                                2      5s
----
--
====

Because this is a `Secret` and not a `ConfigMap`, the user & password are not immediately visible:

[#describe-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl describe secret mysecret
----

[.console-output]
[source,bash]
----
Name:         mysecret
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  10 bytes
user:      10 bytes
----

[#get-secret-cli-yaml-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o yaml
----


[source,yaml]
----
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  user: TXlVc2VyTmFtZQ==
kind: Secret
metadata:
  creationTimestamp: "2020-03-31T20:19:26Z"
  name: mysecret
  namespace: myspace
  resourceVersion: "4944690"
  selfLink: /api/v1/namespaces/myspace/secrets/mysecret
  uid: e8c5f12e-bd71-4d6b-8d8c-7af9ed6439f8
type: Opaque
----

Copy the value of the password field above into the echo command below to prove that it is base64 encoded

[#get-secret-cli-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'bXlwYXNzd29yZA==' | base64 --decode
----

[.console-output]
[source,bash]
----
mypassword
----

[TIP]
====
If pressed for time, you can run the following command instead

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_PASSWORD=$(kubectl get secret mysecret -o jsonpath='{.data.password}')
echo "password:$B64_PASSWORD is decoded as $(echo $B64_PASSWORD | base64 --decode)"
----

====

And then do the same for the username

[#get-secret-cli-username-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'TXlVc2VyTmFtZQ==' | base64 --decode
----

[.console-output]
[source,bash]
----
MyUserName
----

[TIP]
====
If pressed for time, you can run the following command instead

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_DATA=$(kubectl get secret mysecret -o jsonpath='{.data.user}')
echo "username:$B64_DATA is decoded as $(echo $B64_DATA | base64 --decode)"
----

====


Or get them using `kubectl`:

[#get-secret-kubectl-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o jsonpath='{.data.password}' | base64 --decode 
----

== Using Secrets

:quick-open-file: myboot-deployment-configuration-secret.yml

Let's take a look at a deployment, `{quick-open-file}`, that will make use of our newly created secret. 

include::partial$tip_vscode_quick_open.adoc[]

[.console-output]
[source,yaml,subs="+macros,+attributes"]
.{quick-open-file}
----
include::example$myboot-deployment-configuration-secret.yml[]
----
<.> This determines where the pod will find the secret.  It will be in a file in the `/mystuff/secretstuff` directory in the pod
<.> This defines what `mysecretvolume` should actually mount.  In this case `mysecret`, the secret we just created above.

One way to allow deployments (pods) to use secrets is to provide them via Volume Mounts:

[source, yaml]
----
        volumeMounts:          
          - name: mysecretvolume
            mountPath: /mystuff/mysecretvolume
----

Let's update our deployment to use this volume:

[#replace-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl replace -f apps/kubefiles/myboot-deployment-configuration-secret.yml
----

_Once the deployment has been updated_, exec into the newly created Pod:

[#print-secrets-volume-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(kubectl get pod -l app=myboot --field-selector pass:['status.phase!=Terminating'] -o name)
kubectl exec $PODNAME -- ls -l /mystuff/secretstuff
kubectl exec $PODNAME -- cat /mystuff/secretstuff/password
----

Results in:

[.console-output]
[source,bash]
----
total 0
lrwxrwxrwx. 1 root root 15 Jul 19 03:37 password -> ..data/password #<.>
lrwxrwxrwx. 1 root root 11 Jul 19 03:37 user -> ..data/user
mypassword #<.>
----
<.> Refer back to the secret definition.  Each field under the `.data` section of the secret has become a file in this directory that represents the mounted secret
<.> `cat` ing the value of the `password` file gives the value of the `.data.password` field in the `secret` we defined above

[TIP]
====
Alternatively, you can just run the following command to rsh into the pod and poke around

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(kubectl get pod -l app=myboot --field-selector pass:['status.phase!=Terminating'] -o name)
kubectl exec -it $PODNAME -- /bin/bash
----
====


But how would your application know to look in this directory for credentials?  Whilst it could be hardcoded in the application (or via properties) you could also provide the path via of `/mystuff/mysecretvolume` to the pod via an environment variable so the application knows where to go looking.  

[TIP]
====
It's also possible to expose secrets directly as environment variables, but that's beyond the scope of this tutorial
====

For more information on secrets, see https://kubernetes.io/docs/concepts/configuration/secret/[here]

== Clean Up

[.console-input]
[source,bash]
----
kubectl delete deployment myboot
kubectl delete service myboot
----



